[build]
  functions = "functions"
  command = "#"
[template.environment]
  GITHUB_ACCESS_TOKEN = "Generate Personal Access token with repo write:public"
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200
